// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VNAv {z2VRrf ( z2VVej ,) , z2VPoN ( z2VLFK ,) , z2VTYr ( z2VaUr ,) ,} 
pub struct z2VQBL {
    pub field_0: z2VZf9,
    pub field_1: z2VSnT,
}
pub enum z2Ve6M {z2VR63 ( z2VQ3h ,) , z2VTjq ( z2VNBf ,) , z2VRXc ( z2VXAa ,) , z2Vc1N ( z2VQBL ,) , z2VRTb ( z2VT5d ,) , z2VaCt ( z2VR3K ,) ,} 
pub struct z2VQbv(std::string::String);
impl z2VQbv {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaBD(u64);
impl z2VaBD {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2Vb6p {
    pub field_0: Option<z2VecB>,
    pub field_1: Option<z2VTNt>,
}
pub struct z2VYGd(u64);
impl z2VYGd {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VV18(std::string::String);
impl z2VV18 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VLFu {
    pub field_0: Option<z2VUMb>,
    pub field_1: Option<z2VRqc>,
    pub field_2: Option<z2VRQS>,
    pub field_3: Option<z2VYSf>,
    pub field_4: z2VSHd,
    pub field_5: Option<z2VKsS>,
    pub field_6: Option<z2VXxS>,
}
pub enum z2VSnT {z2VVPv ,} 
pub enum z2VXxS {z2VbC1 , z2VeVv ,} 
pub enum z2VR3K {z2VQhq ( z2VUeX ,) , z2VQU1 ( z2VUBQ ,) ,} 
pub struct z2VTNt(u64);
impl z2VTNt {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VRdN {z2Va7M , z2VfEc , z2VNn5 ,} 
pub struct z2VQ3h {
    pub field_0: z2VUN4,
    pub field_1: z2VRg8,
}
pub enum z2VUN4 {z2VZ8M , z2VQdg , z2VdLV , z2VYdH , z2VTxt , z2VS9d ,} 
pub struct z2VLFK ( z2VYGd ,) ;
pub enum z2VKsS {z2VVD9 , z2VVUc , z2VMyX ,} 
pub struct z2VTYs(std::string::String);
impl z2VTYs {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaUr ( z2VMMe ,) ;
pub struct z2VRg8(std::string::String);
impl z2VRg8 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VUeX {
    pub field_0: z2VYGd,
    pub field_1: z2VaBD,
    pub field_2: z2VTct,
}
pub struct z2VNBf ( z2VYGd ,) ;
pub enum z2VSHd {z2VPna , z2Va7b ,} 
pub struct z2VMMe {
    pub field_0: Option<z2VahV>,
    pub field_1: z2VLbX,
    pub field_2: z2VLFu,
}
pub struct z2VecB(u64);
impl z2VecB {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VUBQ {
    pub field_0: z2VYGd,
    pub field_1: z2VbCg,
    pub field_2: z2Vb6p,
}
pub struct z2VTct(std::string::String);
impl z2VTct {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VYSf(u64);
impl z2VYSf {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VRqc(std::string::String);
impl z2VRqc {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VZf9 {z2Vdwh , z2VKzq , z2VRkZ ,} 
pub struct z2VVej ( z2VMMe ,) ;
pub struct z2VL3r {
    pub field_0: z2VYGd,
    pub field_1: z2VT5d,
    pub field_2: z2VR3K,
    pub field_3: z2VYGd,
}
pub struct z2VT5d ( z2VYGd ,) ;
pub struct z2Vav4 {
    pub field_0: z2VRdN,
    pub field_1: z2VV18,
}
pub struct z2VahV(std::string::String);
impl z2VahV {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VXAa {
    pub field_0: z2VTYs,
    pub field_1: z2VbCg,
    pub field_2: z2Vb6p,
}
pub struct z2VbCg(std::string::String);
impl z2VbCg {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VLbX(Vec<z2Vav4>);
impl z2VLbX {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2Vav4>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2Vav4> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2Vav4> {
        self.0
    }
}
pub struct z2VRQS(u64);
impl z2VRQS {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VUMb(std::string::String);
impl z2VUMb {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
