// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
pub use dotos::{DotosDecodeError, DotosEncode, DotosSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UserText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AssistantText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModelName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StreamToken(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TokenDelta(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeltaSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TemperatureMilli(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaximumOutputTokens(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CompletionText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopReasonText(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptTokenCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CompletionTokenCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionDetail(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ChatRole {
    System,
    User,
    Assistant,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChatMessage {
    pub chat_role: ChatRole,
    pub user_text: UserText,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChatTranscript(Vec<ChatMessage>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputMode {
    FreeText,
    Dotos,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReasoningEffort {
    Low,
    Medium,
    High,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ThinkingMode {
    Enabled,
    Disabled,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Model(Option<ModelName>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Provider(Option<ProviderName>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct TemperatureMilliSelection(Option<TemperatureMilli>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct MaximumOutputTokensSelection(Option<MaximumOutputTokens>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ReasoningEffortSelection(Option<ReasoningEffort>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ThinkingModeSelection(Option<ThinkingMode>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptOptions {
    pub(crate) model: Model,
    pub(crate) provider: Provider,
    pub(crate) temperature_milli_selection: TemperatureMilliSelection,
    pub(crate) maximum_output_tokens_selection: MaximumOutputTokensSelection,
    pub output_mode: OutputMode,
    pub(crate) reasoning_effort_selection: ReasoningEffortSelection,
    pub(crate) thinking_mode_selection: ThinkingModeSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct System(Option<SystemText>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Prompt {
    pub(crate) system: System,
    pub chat_transcript: ChatTranscript,
    pub prompt_options: PromptOptions,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct PromptTokens(Option<PromptTokenCount>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct CompletionTokens(Option<CompletionTokenCount>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TokenUsage {
    pub(crate) prompt_tokens: PromptTokens,
    pub(crate) completion_tokens: CompletionTokens,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CallPayload(Prompt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StreamCallPayload(Prompt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CancelStreamPayload(StreamToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Completion {
    pub completion_text: CompletionText,
    pub stop_reason_text: StopReasonText,
    pub token_usage: TokenUsage,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CallRejectionReason {
    NoProviderConfigured,
    ProviderUnreachable,
    ProviderRejected,
    OutputModeUnsupported,
    InvalidDotosOutput,
    DaemonUnconfigured,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CallRejection {
    pub call_rejection_reason: CallRejectionReason,
    pub rejection_detail: RejectionDetail,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StreamOpening(StreamToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StreamCancellation(StreamToken);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Call,
    StreamCall,
    CancelStream,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotInPrototypeScope,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplementedPayload {
    pub operation_kind: OperationKind,
    pub unimplemented_reason: UnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TokenStreamDeltaPayload {
    pub stream_token: StreamToken,
    pub delta_sequence: DeltaSequence,
    pub token_delta: TokenDelta,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CompletionStreamDeltaPayload {
    pub stream_token: StreamToken,
    pub stop_reason_text: StopReasonText,
    pub token_usage: TokenUsage,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AgentEvent {
    TokenStreamDelta(TokenStreamDeltaPayload),
    CompletionStreamDelta(CompletionStreamDeltaPayload),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CompletionStream {
    pub token: StreamToken,
    pub stream_opening: StreamOpening,
    pub agent_event: AgentEvent,
    pub close: StreamToken,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Call(CallPayload),
    StreamCall(StreamCallPayload),
    CancelStream(CancelStreamPayload),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Completed(Completion),
    CallRejected(CallRejection),
    StreamOpened(StreamOpening),
    StreamCancelled(StreamCancellation),
    RequestUnimplemented(RequestUnimplementedPayload),
    Event(AgentEvent),
}

#[rustfmt::skip]
impl SystemText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UserText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for UserText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AssistantText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AssistantText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModelName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ModelName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProviderName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ProviderName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StreamToken {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for StreamToken {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TokenDelta {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TokenDelta {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeltaSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for DeltaSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TemperatureMilli {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TemperatureMilli {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaximumOutputTokens {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MaximumOutputTokens {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CompletionText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for CompletionText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StopReasonText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for StopReasonText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PromptTokenCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for PromptTokenCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CompletionTokenCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CompletionTokenCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectionDetail {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RejectionDetail {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChatTranscript {
    pub fn new(payload: Vec<ChatMessage>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ChatMessage> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ChatMessage> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ChatMessage>> for ChatTranscript {
    fn from(payload: Vec<ChatMessage>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Model {
    pub fn new(payload: Option<ModelName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<ModelName> {
        &self.0
    }
    pub fn into_payload(self) -> Option<ModelName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<ModelName>> for Model {
    fn from(payload: Option<ModelName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Provider {
    pub fn new(payload: Option<ProviderName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<ProviderName> {
        &self.0
    }
    pub fn into_payload(self) -> Option<ProviderName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<ProviderName>> for Provider {
    fn from(payload: Option<ProviderName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TemperatureMilliSelection {
    pub fn new(payload: Option<TemperatureMilli>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<TemperatureMilli> {
        &self.0
    }
    pub fn into_payload(self) -> Option<TemperatureMilli> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<TemperatureMilli>> for TemperatureMilliSelection {
    fn from(payload: Option<TemperatureMilli>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaximumOutputTokensSelection {
    pub fn new(payload: Option<MaximumOutputTokens>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<MaximumOutputTokens> {
        &self.0
    }
    pub fn into_payload(self) -> Option<MaximumOutputTokens> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<MaximumOutputTokens>> for MaximumOutputTokensSelection {
    fn from(payload: Option<MaximumOutputTokens>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReasoningEffortSelection {
    pub fn new(payload: Option<ReasoningEffort>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<ReasoningEffort> {
        &self.0
    }
    pub fn into_payload(self) -> Option<ReasoningEffort> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<ReasoningEffort>> for ReasoningEffortSelection {
    fn from(payload: Option<ReasoningEffort>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThinkingModeSelection {
    pub fn new(payload: Option<ThinkingMode>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<ThinkingMode> {
        &self.0
    }
    pub fn into_payload(self) -> Option<ThinkingMode> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<ThinkingMode>> for ThinkingModeSelection {
    fn from(payload: Option<ThinkingMode>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl System {
    pub fn new(payload: Option<SystemText>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<SystemText> {
        &self.0
    }
    pub fn into_payload(self) -> Option<SystemText> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<SystemText>> for System {
    fn from(payload: Option<SystemText>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PromptTokens {
    pub fn new(payload: Option<PromptTokenCount>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<PromptTokenCount> {
        &self.0
    }
    pub fn into_payload(self) -> Option<PromptTokenCount> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<PromptTokenCount>> for PromptTokens {
    fn from(payload: Option<PromptTokenCount>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CompletionTokens {
    pub fn new(payload: Option<CompletionTokenCount>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<CompletionTokenCount> {
        &self.0
    }
    pub fn into_payload(self) -> Option<CompletionTokenCount> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<CompletionTokenCount>> for CompletionTokens {
    fn from(payload: Option<CompletionTokenCount>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CallPayload {
    pub fn new(payload: Prompt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Prompt {
        &self.0
    }
    pub fn into_payload(self) -> Prompt {
        self.0
    }
}
#[rustfmt::skip]
impl From<Prompt> for CallPayload {
    fn from(payload: Prompt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StreamCallPayload {
    pub fn new(payload: Prompt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Prompt {
        &self.0
    }
    pub fn into_payload(self) -> Prompt {
        self.0
    }
}
#[rustfmt::skip]
impl From<Prompt> for StreamCallPayload {
    fn from(payload: Prompt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CancelStreamPayload {
    pub fn new(payload: StreamToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StreamToken {
        &self.0
    }
    pub fn into_payload(self) -> StreamToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<StreamToken> for CancelStreamPayload {
    fn from(payload: StreamToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StreamOpening {
    pub fn new(payload: StreamToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StreamToken {
        &self.0
    }
    pub fn into_payload(self) -> StreamToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<StreamToken> for StreamOpening {
    fn from(payload: StreamToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StreamCancellation {
    pub fn new(payload: StreamToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StreamToken {
        &self.0
    }
    pub fn into_payload(self) -> StreamToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<StreamToken> for StreamCancellation {
    fn from(payload: StreamToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentEvent {
    pub fn token_stream_delta(payload: TokenStreamDeltaPayload) -> Self {
        Self::TokenStreamDelta(payload)
    }
    pub fn completion_stream_delta(payload: CompletionStreamDeltaPayload) -> Self {
        Self::CompletionStreamDelta(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn call(payload: Prompt) -> Self {
        Self::Call(CallPayload::new(payload))
    }
    pub fn stream_call(payload: Prompt) -> Self {
        Self::StreamCall(StreamCallPayload::new(payload))
    }
    pub fn cancel_stream(payload: StreamToken) -> Self {
        Self::CancelStream(CancelStreamPayload::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn completed(payload: Completion) -> Self {
        Self::Completed(payload)
    }
    pub fn call_rejected(payload: CallRejection) -> Self {
        Self::CallRejected(payload)
    }
    pub fn stream_opened(payload: StreamToken) -> Self {
        Self::StreamOpened(StreamOpening::new(payload))
    }
    pub fn stream_cancelled(payload: StreamToken) -> Self {
        Self::StreamCancelled(StreamCancellation::new(payload))
    }
    pub fn request_unimplemented(payload: RequestUnimplementedPayload) -> Self {
        Self::RequestUnimplemented(payload)
    }
    pub fn event(payload: AgentEvent) -> Self {
        Self::Event(payload)
    }
}

#[rustfmt::skip]
impl From<TokenStreamDeltaPayload> for AgentEvent {
    fn from(payload: TokenStreamDeltaPayload) -> Self {
        Self::TokenStreamDelta(payload)
    }
}

#[rustfmt::skip]
impl From<CompletionStreamDeltaPayload> for AgentEvent {
    fn from(payload: CompletionStreamDeltaPayload) -> Self {
        Self::CompletionStreamDelta(payload)
    }
}

#[rustfmt::skip]
impl From<CallPayload> for Input {
    fn from(payload: CallPayload) -> Self {
        Self::Call(payload)
    }
}

#[rustfmt::skip]
impl From<StreamCallPayload> for Input {
    fn from(payload: StreamCallPayload) -> Self {
        Self::StreamCall(payload)
    }
}

#[rustfmt::skip]
impl From<CancelStreamPayload> for Input {
    fn from(payload: CancelStreamPayload) -> Self {
        Self::CancelStream(payload)
    }
}

#[rustfmt::skip]
impl From<Completion> for Output {
    fn from(payload: Completion) -> Self {
        Self::Completed(payload)
    }
}

#[rustfmt::skip]
impl From<CallRejection> for Output {
    fn from(payload: CallRejection) -> Self {
        Self::CallRejected(payload)
    }
}

#[rustfmt::skip]
impl From<StreamOpening> for Output {
    fn from(payload: StreamOpening) -> Self {
        Self::StreamOpened(payload)
    }
}

#[rustfmt::skip]
impl From<StreamCancellation> for Output {
    fn from(payload: StreamCancellation) -> Self {
        Self::StreamCancelled(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplementedPayload> for Output {
    fn from(payload: RequestUnimplementedPayload) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEvent> for Output {
    fn from(payload: AgentEvent) -> Self {
        Self::Event(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Input {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Output {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CALL: u64 = 0x0000000100000001;
    pub const INPUT_STREAM_CALL: u64 = 0x0001000100000001;
    pub const INPUT_CANCEL_STREAM: u64 = 0x0002000100000001;
    pub const OUTPUT_COMPLETED: u64 = 0x0100000100000001;
    pub const OUTPUT_CALL_REJECTED: u64 = 0x0101000100000001;
    pub const OUTPUT_STREAM_OPENED: u64 = 0x0102000100000001;
    pub const OUTPUT_STREAM_CANCELLED: u64 = 0x0103000100000001;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0104000100000001;
    pub const OUTPUT_EVENT: u64 = 0x0105000100000001;
    pub const HANDSHAKE_REQUEST: u64 = 0xFF00000100000001;
    pub const HANDSHAKE_REPLY: u64 = 0xFF01000100000001;
    pub const ENGINE_REFUSAL: u64 = 0xFF02000100000001;
}

#[rustfmt::skip]
pub enum ContractMarker {}
#[rustfmt::skip]
impl signal_frame::WireContract for ContractMarker {
    const BINDING: signal_frame::ContractBinding = signal_frame::ContractBinding::new(
        match signal_frame::ContractId::try_new(1u32) {
            Ok(contract) => contract,
            Err(_) => panic!("generated contract ID must be nonzero"),
        },
        match signal_frame::WireRevision::try_new(1u16) {
            Ok(revision) => revision,
            Err(_) => panic!("generated wire revision must be nonzero"),
        },
    );
}
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_bound_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            signal_frame::SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&short_header::ENGINE_REFUSAL.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    FrameEncode,
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    LegacyHeader { contract_id: u32, wire_revision: u16 },
    ContractMismatch { expected: u32, found: u32 },
    UnsupportedWireRevision { contract_id: u32, expected: u16, found: u16 },
    UnknownRoute { root: u8, variant: u8 },
    RouteBodyMismatch { root: u8, variant: u8, body: &'static str },
    UnexpectedFrameBody { found: &'static str },
    OperationCount { found: usize },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FrameEncode => {
                formatter.write_str("failed to encode bound signal frame")
            }
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::LegacyHeader { contract_id, wire_revision } => {
                write!(
                    formatter,
                    "legacy unbound signal frame ({contract_id}, {wire_revision})"
                )
            }
            Self::ContractMismatch { expected, found } => {
                write!(
                    formatter,
                    "signal contract mismatch: expected {expected}, found {found}"
                )
            }
            Self::UnsupportedWireRevision { contract_id, expected, found } => {
                write!(
                    formatter,
                    "unsupported wire revision for contract {contract_id}: expected {expected}, found {found}"
                )
            }
            Self::UnknownRoute { root, variant } => {
                write!(formatter, "unknown bound signal route ({root}, {variant})")
            }
            Self::RouteBodyMismatch { root, variant, body } => {
                write!(
                    formatter,
                    "bound signal route ({root}, {variant}) does not carry {body}"
                )
            }
            Self::UnexpectedFrameBody { found } => {
                write!(formatter, "expected one request frame, found {found}")
            }
            Self::OperationCount { found } => {
                write!(formatter, "expected one request operation, found {found}")
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}
#[rustfmt::skip]
impl ContractMarker {
    pub fn handshake_request_frame(request: signal_frame::HandshakeRequest) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(0),
            ),
            FrameBody::HandshakeRequest(request),
        )
    }
    pub fn handshake_reply_frame(reply: signal_frame::HandshakeReply) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(1),
            ),
            FrameBody::HandshakeReply(reply),
        )
    }
    pub fn decode_frame(bytes: &[u8]) -> Result<Frame, SignalFrameError> {
        if bytes.len() < signal_frame::SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: bytes.len(),
            });
        }
        let mut header_bytes = [0_u8; signal_frame::SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&bytes[..signal_frame::SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let contract_id = header as u32;
        let wire_revision = (header >> 32) as u16;
        if contract_id == 0 || wire_revision == 0 {
            return Err(SignalFrameError::LegacyHeader {
                contract_id,
                wire_revision,
            });
        }
        if contract_id != 1u32 {
            return Err(SignalFrameError::ContractMismatch {
                expected: 1u32,
                found: contract_id,
            });
        }
        if wire_revision != 1u16 {
            return Err(SignalFrameError::UnsupportedWireRevision {
                contract_id,
                expected: 1u16,
                found: wire_revision,
            });
        }
        let root = (header >> 56) as u8;
        let variant = (header >> 48) as u8;
        match (root, variant) {
            (0, 0)
            | (0, 1)
            | (0, 2)
            | (1, 0)
            | (1, 1)
            | (1, 2)
            | (1, 3)
            | (1, 4)
            | (1, 5)
            | (0xff, 0)
            | (0xff, 1)
            | (0xff, 2) => {}
            _ => {
                return Err(SignalFrameError::UnknownRoute {
                    root,
                    variant,
                });
            }
        }
        if (root, variant) == (0xff, 2) {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&bytes[signal_frame::SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let frame = Frame::decode(bytes).map_err(|_| SignalFrameError::ArchiveDecode)?;
        let header_route = signal_frame::WireRoute::new(
            signal_frame::RootCode::new(root),
            signal_frame::VariantCode::new(variant),
        );
        let body_matches = match frame.body() {
            FrameBody::HandshakeRequest(_) => (root, variant) == (0xff, 0),
            FrameBody::HandshakeReply(_) => (root, variant) == (0xff, 1),
            FrameBody::Request { request, .. } => {
                request.route().is_ok_and(|route| route == header_route)
            }
            FrameBody::Reply { reply, .. } => {
                match reply {
                    signal_frame::Reply::Accepted { per_operation, .. } => {
                        match per_operation.head() {
                            signal_frame::SubReply::Ok(output) => {
                                output.wire_route() == header_route
                            }
                            signal_frame::SubReply::Failed {
                                detail: Some(output),
                                ..
                            } => output.wire_route() == header_route,
                            signal_frame::SubReply::Invalidated
                            | signal_frame::SubReply::Failed { detail: None, .. }
                            | signal_frame::SubReply::Skipped => root == 1,
                        }
                    }
                    signal_frame::Reply::Rejected { .. } => root == 1,
                }
            }
        };
        if !body_matches {
            let body = match frame.body() {
                FrameBody::HandshakeRequest(_) => "handshake request",
                FrameBody::HandshakeReply(_) => "handshake reply",
                FrameBody::Request { .. } => "request",
                FrameBody::Reply { .. } => "reply",
            };
            return Err(SignalFrameError::RouteBodyMismatch {
                root,
                variant,
                body,
            });
        }
        Ok(frame)
    }
    pub fn decode_single_request(
        bytes: &[u8],
    ) -> Result<(signal_frame::ExchangeIdentifier, Input), SignalFrameError> {
        let frame = Self::decode_frame(bytes)?;
        match frame.into_body() {
            FrameBody::Request { exchange, request } => {
                let found = request.payloads().len();
                if found != 1 {
                    return Err(SignalFrameError::OperationCount {
                        found,
                    });
                }
                Ok((exchange, request.payloads.into_head()))
            }
            FrameBody::HandshakeRequest(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake request",
                })
            }
            FrameBody::HandshakeReply(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake reply",
                })
            }
            FrameBody::Reply { .. } => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "reply",
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Call,
    StreamCall,
    CancelStream,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Completed,
    CallRejected,
    StreamOpened,
    StreamCancelled,
    RequestUnimplemented,
    Event,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Call(_) => InputRoute::Call,
            Self::StreamCall(_) => InputRoute::StreamCall,
            Self::CancelStream(_) => InputRoute::CancelStream,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Call(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::StreamCall(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::CancelStream(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(2),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Call(_) => short_header::INPUT_CALL,
            Self::StreamCall(_) => short_header::INPUT_STREAM_CALL,
            Self::CancelStream(_) => short_header::INPUT_CANCEL_STREAM,
        }
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Completed(_) => OutputRoute::Completed,
            Self::CallRejected(_) => OutputRoute::CallRejected,
            Self::StreamOpened(_) => OutputRoute::StreamOpened,
            Self::StreamCancelled(_) => OutputRoute::StreamCancelled,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
            Self::Event(_) => OutputRoute::Event,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Completed(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::CallRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::StreamOpened(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::StreamCancelled(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::RequestUnimplemented(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(4),
                )
            }
            Self::Event(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(5),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Completed(_) => short_header::OUTPUT_COMPLETED,
            Self::CallRejected(_) => short_header::OUTPUT_CALL_REJECTED,
            Self::StreamOpened(_) => short_header::OUTPUT_STREAM_OPENED,
            Self::StreamCancelled(_) => short_header::OUTPUT_STREAM_CANCELLED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
            Self::Event(_) => short_header::OUTPUT_EVENT,
        }
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Call", "StreamCall", "CancelStream"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        let route = self.wire_route();
        u64::from(route.root().value()) | (u64::from(route.variant().value()) << 8)
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::BoundExchangeFrame<ContractMarker, Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let request = signal_frame::Request::from_payload(self);
        Frame::new(
            route,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
    pub fn encode_request_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_frame(exchange).encode().map_err(|_| SignalFrameError::FrameEncode)
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::new(
            route,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
    pub fn encode_reply_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_reply_frame(exchange)
            .encode()
            .map_err(|_| SignalFrameError::FrameEncode)
    }
}
